### ISSUE TITLE
Amounts of each NFT are not tracked

### ISSUE THREAD

**Issue by jjc6676** [Sewersidesquad/MintTracker#3]
It seems that if the amount of each NFT you hold in the wallet is more than one, that is not tracked.
Only the one is tracked.

Can you implement a numbers column of how many of each NFT the wallet owns perhaps?

**Comment by Sewersidesquad** [comment]
I'll try to implement something it could get a little messy in the spreadsheet, I'm unfortunately not that familiar with spreadsheets. So I wouldn't really know where to start when cleaning it up.

**Comment by Sewersidesquad** [comment]
Added
